EXTENDED_TYPES_DEFAULT_FIELDS = {
    'CaseStudy':[
        'id',
        'title',
        'description',
        'isNews',
        'text', 
        'displayImages', 
        'action', 
        'results', 
        'publication_year', 
        'organisation', 
        'remoteLanguage', 
        'remoteUrl', 
        'displayAttachments', 
        'subject', 
        'relatedItems', 
        'location', 
        'osha_metadata', 
        'nace', 
        'country', 
        'multilingual_thesaurus', 
        'reindexTranslations', 
        ],

    # In osha.policy/patches/event_patch.py, finalizeATCTSchema
    # is called which moveѕ the location field away from the
    # default schemata to categorization. While testing though,
    # this is not the case, and we have to include location.
    'Event': [
        'id',
        'title',
        'description',
        'isNews',
        'startDate',
        'endDate',
        'text',
        'attendees',
        'eventType',
        'eventUrl',
        'contactName',
        'contactEmail',
        'contactPhone',
        'subcategory',
        'multilingual_thesaurus',
        'osha_metadata',
        'attachment',
        'reindexTranslations',
        'location', 
        ],

    "Link" : [
        'id',
        'title',
        'description',
        'isNews',
        'remoteUrl',
        'country',
        'subcategory',
        'multilingual_thesaurus',
        'nace',
        'reindexTranslations',
        ],

    "Image" : [
        'id',
        'title',
        'description',
        'isNews',
        'country',
        'subcategory',
        'multilingual_thesaurus',
        'nace',
        'reindexTranslations',
        'image',
        ],

    "Document" : [
        'id',
        'title',
        'description',
        'text',
        'country',
        'multilingual_thesaurus',
        'nace',
        'osha_metadata',
        'reindexTranslations',
        ],

    "RichDocument" : [
        'id',
        'title',
        'description',
        'text',
        'displayImages',
        'displayAttachments',
        'country',
        'multilingual_thesaurus',
        'nace',
        'osha_metadata',
        'reindexTranslations',
        ],

    "News Item" : [
        'id',
        'title',
        'description',
        'text',
        'image',
        'imageCaption',
        'country',
        'multilingual_thesaurus',
        'nace',
        'osha_metadata',
        'reindexTranslations',
        ],

    "RALink" : [
        'id',
        'title',
        'description',
        'isNews',
        'text',
        'remoteUrl',
        'remoteLanguage',
        'country',
        'remoteProvider',
        'multilingual_thesaurus',
        'nace',
        'dateOfEditing',
        'occupation',
        'ra_contents',
        'type_methodology',
        'subject',
        'allowDiscussion',
        'excludeFromNav',
        'tableContents',
        'presentation',
        'relatedItems',
        'location',
        'osha_metadata',
        'reindexTranslations',
        ],

    "OSH_Link" : [
        'id',
        'title',
        'description',
        'isNews',
        'text',
        'remoteUrl',
        'provider',
        'remoteProvider',
        'remoteLanguage',
        'country',
        'subcategory',
        'multilingual_thesaurus',
        'nace',
        'cas',
        'einecs',
        'general_comments',
        'author',
        'printref',
        'organisation_name',
        'isbn_d',
        'publication_date',
        'relatedItems',
        'language',
        'location',
        'excludeFromNav',
        'tableContents',
        'presentation',
        'allowDiscussion',
        'effectiveDate',
        'expirationDate',
        'reindexTranslations',
        ],

    "PressRelease" : [
        'id',
        'releaseTiming',
        'title',
        'subhead',
        'releaseDate',
        'description',
        'text',
        'image',
        'imageCaption',
        'releaseContacts',
        'osha_metadata',
        'referenced_content',
        'isNews',
        'country',
        'reindexTranslations',
        ],

    "Provider" : [
        'id',
        'title',
        'description',
        'remoteUrl',
        'providerCategory',
        'remoteLanguage',
        'location',
        'effectiveDate',
        'expirationDate',
        'country',
        'subcategory',
        'multilingual_thesaurus',
        'nace',
        'isNews',
        'reindexTranslations',
    ],
    }

    # "SPSpeaker" : [
    #     'id',
    #     'title',
    #     'firstName',
    #     'middleName',
    #     'lastName',
    #     'suffix',
    #     'email',
    #     'jobTitles',
    #     'officeAddress',
    #     'officeCity',
    #     'officeState',
    #     'officePostalCode',
    #     'officePhone',
    #     'image',
    #     'biography',
    #     'education',
    #     'website',
    #     'speeches',
    #     'nationality',
    #     'employer',
    #     'socialPartnerGroup',
    #     'expertise',
    #     'country',
    #     'subcategory',
    #     'multilingual_thesaurus',
    #     'nace',
    #     'isNews',
    #     'reindexTranslations',
    #     ],

    # "SPSpeechVenue" : [
    #     'id',
    #     'title',
    #     'description',
    #     'isNews',
    #     'constrainTypesMode',
    #     'locallyAllowedTypes',
    #     'immediatelyAddableTypes',
    #     'country',
    #     'subcategory',
    #     'multilingual_thesaurus',
    #     'nace',
    #     'reindexTranslations',
    #     ],

    # 'HelpCenterFAQ': [
    #     'id',
    #     'title',
    #     'allowDiscussion',
    #     'description',
    #     'location',
    #     'creators',
    #     'effectiveDate',
    #     'expirationDate',
    #     'language',
    #     'creation_date',
    #     'modification_date',
    #     'answer',
    #     'versions',
    #     'sections',
    #     'contributors',
    #     'startHere',
    #     'subject',
    #     'relatedItems',
    #     'subcategory',
    #     'nace',
    #     'multilingual_thesaurus',
    #     ],

    # "File" : [
    #     'id',
    #     'title',
    #     'description',
    #     'isNews',
    #     'country',
    #     'subcategory',
    #     'multilingual_thesaurus',
    #     'nace',
    #     'reindexTranslations',
    #     'file',
    #     ],
