EXTENDED_TYPES_DEFAULT_FIELDS = {
    'CaseStudy': {
        'id':                       {'edit': 'invisible', 'view': 'invisible'},
        'title':                    {'edit': 'visible',   'view': 'visible'},    
        'description':              {'edit': 'visible',   'view': 'visible'},       
        'isNews':                   {'edit': 'visible',   'view': 'visible'},    
        'text':                     {'edit': 'visible',   'view': 'visible'},    
        'displayImages':            {'edit': 'visible',   'view': 'visible'},    
        'action':                   {'edit': 'visible',   'view': 'visible'},    
        'results':                  {'edit': 'visible',   'view': 'visible'},    
        'publication_year':         {'edit': 'visible',   'view': 'visible'},    
        'organisation':             {'edit': 'visible',   'view': 'visible'},    
        'remoteLanguage':           {'edit': 'visible',   'view': 'visible'},    
        'remoteUrl':                {'edit': 'visible',   'view': 'visible'},    
        'displayAttachments':       {'edit': 'visible',   'view': 'visible'},    
        'subject':                  {'edit': 'visible',   'view': 'visible'},    
        'relatedItems':             {'edit': 'visible',   'view': 'visible'},    
        'location':                 {'edit': 'visible',   'view': 'visible'},    
        'osha_metadata':            {'edit': 'visible',   'view': 'visible'},    
        'nace':                     {'edit': 'visible',   'view': 'visible'},    
        'country':                  {'edit': 'visible',   'view': 'visible'},    
        'multilingual_thesaurus':   {'edit': 'visible',   'view': 'visible'},    
        'reindexTranslations':      {'edit': 'visible',   'view': 'visible'},    
        },

    'Event': {
        'id':                       {'edit': 'invisible', 'view': 'invisible'},                          
        'title':                    {'edit': 'visible',   'view': 'visible'},                                 
        'description':              {'edit': 'visible',   'view': 'visible'},                                       
        'isNews':                   {'edit': 'visible',   'view': 'visible'},                                  
        'startDate':                {'edit': 'visible',   'view': 'visible'},                                     
        'endDate':                  {'edit': 'visible',   'view': 'visible'},                                   
        'text':                     {'edit': 'visible',   'view': 'visible'},                                
        'attendees':                {'edit': 'visible',   'view': 'visible'},                                     
        'eventType':                {'edit': 'visible',   'view': 'visible'},                                     
        'eventUrl':                 {'edit': 'visible',   'view': 'visible'},                                    
        'contactName':              {'edit': 'visible',   'view': 'visible'},                                       
        'contactEmail':             {'edit': 'visible',   'view': 'visible'},                                        
        'contactPhone':             {'edit': 'visible',   'view': 'visible'},                                        
        'subcategory':              {'edit': 'visible',   'view': 'visible'},                                       
        'multilingual_thesaurus':   {'edit': 'visible',   'view': 'visible'},                                                  
        'osha_metadata':            {'edit': 'visible',   'view': 'visible'},                                         
        'attachment':               {'edit': 'visible',   'view': 'visible'},                                      
        'reindexTranslations':      {'edit': 'visible',   'view': 'visible'},                                               
        },                          
                                    
    "Link": {                        
        'id':                       {'edit': 'invisible', 'view': 'invisible'},
        'title':                    {'edit': 'visible',   'view': 'visible'},                                                
        'description':              {'edit': 'visible',   'view': 'visible'},                                                
        'isNews':                   {'edit': 'visible',   'view': 'visible'},                                                
        'remoteUrl':                {'edit': 'visible',   'view': 'visible'},                                                
        'country':                  {'edit': 'visible',   'view': 'visible'},                                                
        'subcategory':              {'edit': 'visible',   'view': 'visible'},                                                
        'multilingual_thesaurus':   {'edit': 'visible',   'view': 'visible'},                                                
        'nace':                     {'edit': 'visible',   'view': 'visible'},                                                
        'reindexTranslations':      {'edit': 'visible',   'view': 'visible'},                                                
        },

    "ATFile": {                       
        'id':                       {'edit': 'invisible',   'view': 'visible'},                                                
        'title':                    {'edit': 'visible',   'view': 'visible'},                                                
        'description':              {'edit': 'visible',   'view': 'visible'},                                                
        'isNews':                   {'edit': 'visible',   'view': 'visible'},                                                
        'country':                  {'edit': 'visible',   'view': 'visible'},                                                
        'subcategory':              {'edit': 'visible',   'view': 'visible'},                                                
        'multilingual_thesaurus':   {'edit': 'visible',   'view': 'visible'},                                                
        'nace':                     {'edit': 'visible',   'view': 'visible'},                                                
        'reindexTranslations':      {'edit': 'visible',   'view': 'visible'},                                                
        'file':                     {'edit': 'visible',   'view': 'visible'},                                                
        },

    "Image": {                       
        'id':                       {'edit': 'invisible', 'view': 'visible'},                                                
        'title':                    {'edit': 'visible',   'view': 'visible'},                                                
        'description':              {'edit': 'visible',   'view': 'visible'},                                                
        'isNews':                   {'edit': 'visible',   'view': 'visible'},                                                
        'country':                  {'edit': 'visible',   'view': 'visible'},                                                
        'subcategory':              {'edit': 'visible',   'view': 'visible'},                                                
        'multilingual_thesaurus':   {'edit': 'visible',   'view': 'visible'},                                                
        'nace':                     {'edit': 'visible',   'view': 'visible'},                                                
        'reindexTranslations':      {'edit': 'visible',   'view': 'visible'},                                                
        'image':                    {'edit': 'visible',   'view': 'visible'},                                                
        },

    "Document": {
        'id':                       {'edit': 'invisible', 'view': 'invisible'},                                                
        'title':                    {'edit': 'visible',   'view': 'visible'},                                                
        'description':              {'edit': 'visible',   'view': 'visible'},                                                
        'text':                     {'edit': 'visible',   'view': 'visible'},                                                
        'country':                  {'edit': 'visible',   'view': 'visible'},                                                
        'multilingual_thesaurus':   {'edit': 'visible',   'view': 'visible'},                                                
        'nace':                     {'edit': 'visible',   'view': 'visible'},                                                
        'osha_metadata':            {'edit': 'visible',   'view': 'visible'},                                                
        'reindexTranslations':      {'edit': 'visible',   'view': 'visible'},                                                
        },

    "RichDocument": {              
        'id':                       {'edit': 'invisible', 'view': 'invisible'},                                                
        'title':                    {'edit': 'visible',   'view': 'visible'},                                                
        'description':              {'edit': 'visible',   'view': 'visible'},                                                
        'text':                     {'edit': 'visible',   'view': 'visible'},                                                
        'displayImages':            {'edit': 'visible',   'view': 'visible'},                                                
        'displayAttachments':       {'edit': 'visible',   'view': 'visible'},                                                
        'country':                  {'edit': 'visible',   'view': 'visible'},                                                
        'multilingual_thesaurus':   {'edit': 'visible',   'view': 'visible'},                                                
        'nace':                     {'edit': 'visible',   'view': 'visible'},                                                
        'osha_metadata':            {'edit': 'visible',   'view': 'visible'},                                                
        'reindexTranslations':      {'edit': 'visible',   'view': 'visible'},                                                
        },

    "News Item": {                
        'id':                       {'edit': 'invisible', 'view': 'invisible'},                                                 
        'title':                    {'edit': 'visible',   'view': 'visible'},                                                
        'description':              {'edit': 'visible',   'view': 'visible'},                                                
        'text':                     {'edit': 'visible',   'view': 'visible'},                                                
        'image':                    {'edit': 'visible',   'view': 'visible'},                                                
        'imageCaption':             {'edit': 'visible',   'view': 'visible'},                                                
        'country':                  {'edit': 'visible',   'view': 'visible'},                                                
        'multilingual_thesaurus':   {'edit': 'visible',   'view': 'visible'},                                                
        'nace':                     {'edit': 'visible',   'view': 'visible'},                                                
        'osha_metadata':            {'edit': 'visible',   'view': 'visible'},                                                
        'reindexTranslations':      {'edit': 'visible',   'view': 'visible'},                                                
        },

    "RALink" : {
        'id':                       {'edit': 'invisible', 'view': 'invisible'},                                                 
        'title':                    {'edit': 'visible',   'view': 'visible'},                                                
        'description':              {'edit': 'visible',   'view': 'visible'},                                                
        'isNews':                   {'edit': 'visible',   'view': 'visible'},                                                
        'text':                     {'edit': 'visible',   'view': 'visible'},                                                
        'remoteUrl':                {'edit': 'visible',   'view': 'visible'},                                                
        'remoteLanguage':           {'edit': 'visible',   'view': 'visible'},                                                
        'country':                  {'edit': 'visible',   'view': 'visible'},                                                
        'remoteProvider':           {'edit': 'visible',   'view': 'visible'},                                                
        'multilingual_thesaurus':   {'edit': 'visible',   'view': 'visible'},                                                
        'nace':                     {'edit': 'visible',   'view': 'visible'},                                                
        'dateOfEditing':            {'edit': 'visible',   'view': 'visible'},                                                
        'occupation':               {'edit': 'visible',   'view': 'visible'},                                                
        'ra_contents':              {'edit': 'visible',   'view': 'visible'},                                                
        'type_methodology':         {'edit': 'visible',   'view': 'visible'},                                                
        'subject':                  {'edit': 'visible',   'view': 'visible'},                                                
        'allowDiscussion':          {'edit': 'visible',   'view': 'visible'},                                                
        'excludeFromNav':           {'edit': 'visible',   'view': 'visible'},                                                
        'tableContents':            {'edit': 'visible',   'view': 'visible'},                                                
        'presentation':             {'edit': 'visible',   'view': 'visible'},                                                
        'relatedItems':             {'edit': 'visible',   'view': 'visible'},                                                
        'location':                 {'edit': 'visible',   'view': 'visible'},                                                
        'osha_metadata':            {'edit': 'visible',   'view': 'visible'},                                                
        'reindexTranslations':      {'edit': 'visible',   'view': 'visible'},                                                
        },

    "OSH_Link" : {
        'id':                       {'edit': 'invisible', 'view': 'invisible'},                                                 
        'title':                    {'edit': 'visible',   'view': 'visible'},                                                
        'description':              {'edit': 'visible',   'view': 'visible'},                                                
        'isNews':                   {'edit': 'visible',   'view': 'visible'},                                                
        'text':                     {'edit': 'visible',   'view': 'visible'},                                                
        'remoteUrl':                {'edit': 'visible',   'view': 'visible'},                                                
        'provider':                 {'edit': 'visible',   'view': 'visible'},                                                
        'remoteProvider':           {'edit': 'visible',   'view': 'visible'},                                                
        'remoteLanguage':           {'edit': 'visible',   'view': 'visible'},                                                
        'country':                  {'edit': 'visible',   'view': 'visible'},                                                
        'subcategory':              {'edit': 'visible',   'view': 'visible'},                                                
        'multilingual_thesaurus':   {'edit': 'visible',   'view': 'visible'},                                                
        'nace':                     {'edit': 'visible',   'view': 'visible'},                                                
        'cas':                      {'edit': 'visible',   'view': 'visible'},                                                
        'einecs':                   {'edit': 'visible',   'view': 'visible'},                                                
        'general_comments':         {'edit': 'visible',   'view': 'visible'},                                                
        'author':                   {'edit': 'visible',   'view': 'visible'},                                                
        'printref':                 {'edit': 'visible',   'view': 'visible'},                                                
        'organisation_name':        {'edit': 'visible',   'view': 'visible'},                                                
        'isbn_d':                   {'edit': 'visible',   'view': 'visible'},                                                
        'publication_date':         {'edit': 'visible',   'view': 'visible'},                                                
        'relatedItems':             {'edit': 'visible',   'view': 'visible'},                                                
        'language':                 {'edit': 'visible',   'view': 'visible'},                                                
        'location':                 {'edit': 'visible',   'view': 'visible'},                                                
        'excludeFromNav':           {'edit': 'visible',   'view': 'visible'},                                                
        'tableContents':            {'edit': 'visible',   'view': 'visible'},                                                
        'presentation':             {'edit': 'visible',   'view': 'visible'},                                                
        'allowDiscussion':          {'edit': 'visible',   'view': 'visible'},                                                
        'effectiveDate':            {'edit': 'visible',   'view': 'visible'},                                                
        'expirationDate':           {'edit': 'visible',   'view': 'visible'},                                                
        'reindexTranslations':      {'edit': 'visible',   'view': 'visible'},                                                
        },

    "PressRelease": {
        'id':                       {'edit': 'invisible', 'view': 'invisible'},                                                
        'releaseTiming':            {'edit': 'visible',   'view': 'visible'},                                                
        'title':                    {'edit': 'visible',   'view': 'visible'},                                                
        'subhead':                  {'edit': 'visible',   'view': 'visible'},                                                
        'releaseDate':              {'edit': 'visible',   'view': 'visible'},                                                
        'description':              {'edit': 'visible',   'view': 'visible'},                                                
        'text':                     {'edit': 'visible',   'view': 'visible'},                                                
        'image':                    {'edit': 'visible',   'view': 'visible'},                                                
        'imageCaption':             {'edit': 'visible',   'view': 'visible'},                                                
        'releaseContacts':          {'edit': 'visible',   'view': 'visible'},                                                
        'osha_metadata':            {'edit': 'visible',   'view': 'visible'},                                                
        'referenced_content':       {'edit': 'visible',   'view': 'visible'},                                                
        'isNews':                   {'edit': 'visible',   'view': 'visible'},                                                
        'country':                  {'edit': 'visible',   'view': 'visible'},                                                
        'reindexTranslations':      {'edit': 'visible',   'view': 'visible'},                                                
        },

    "Provider": {
        'id':                       {'edit': 'invisible', 'view': 'invisible'},                                                 
        'title':                    {'edit': 'visible',   'view': 'visible'},                                                
        'description':              {'edit': 'visible',   'view': 'visible'},                                                
        'remoteUrl':                {'edit': 'visible',   'view': 'visible'},                                                
        'providerCategory':         {'edit': 'visible',   'view': 'visible'},                                                
        'remoteLanguage':           {'edit': 'visible',   'view': 'visible'},                                                
        'location':                 {'edit': 'visible',   'view': 'visible'},                                                
        'effectiveDate':            {'edit': 'visible',   'view': 'visible'},                                                
        'expirationDate':           {'edit': 'visible',   'view': 'visible'},                                                
        'country':                  {'edit': 'visible',   'view': 'visible'},                                                
        'subcategory':              {'edit': 'visible',   'view': 'visible'},                                                
        'multilingual_thesaurus':   {'edit': 'visible',   'view': 'visible'},                                                
        'nace':                     {'edit': 'visible',   'view': 'visible'},                                                
        'isNews':                   {'edit': 'visible',   'view': 'visible'},                                                
        'reindexTranslations':      {'edit': 'visible',   'view': 'visible'},                                                
        },

    'HelpCenterFAQ': {
        'id':                       {'edit': 'invisible', 'view': 'invisible'},                                                 
        'title':                    {'edit': 'visible',   'view': 'visible'},                                                
        'description':              {'edit': 'visible',   'view': 'visible'},                                                
        'answer':                   {'edit': 'visible',   'view': 'visible'},                                                
        'versions':                 {'edit': 'visible',   'view': 'visible'},                                                
        'sections':                 {'edit': 'visible',   'view': 'visible'},                                                
        'contributors':             {'edit': 'visible',   'view': 'visible'},                                                
        'startHere':                {'edit': 'visible',   'view': 'visible'},                                                
        'subject':                  {'edit': 'visible',   'view': 'visible'},                                                
        'relatedItems':             {'edit': 'visible',   'view': 'visible'},                                                
        'subcategory':              {'edit': 'visible',   'view': 'visible'},                                                
        'nace':                     {'edit': 'visible',   'view': 'visible'},                                                
        'multilingual_thesaurus':   {'edit': 'visible',   'view': 'visible'},                                                
        },

    'SPSpeechVenue': {
        'id':                       {'edit': 'invisible', 'view': 'invisible'},                                                 
        'title':                    {'edit': 'visible',   'view': 'visible'},                                                
        'description':              {'edit': 'visible',   'view': 'visible'},                                                
        'isNews':                   {'edit': 'visible',   'view': 'visible'},                                                
        'constrainTypesMode':       {'edit': 'visible',   'view': 'visible'},                                                
        'locallyAllowedTypes':      {'edit': 'visible',   'view': 'visible'},                                                
        'immediatelyAddableTypes':  {'edit': 'visible',   'view': 'visible'},                                                
        'country':                  {'edit': 'visible',   'view': 'visible'},                                                
        'subcategory':              {'edit': 'visible',   'view': 'visible'},                                                
        'multilingual_thesaurus':   {'edit': 'visible',   'view': 'visible'},                                                
        'nace':                     {'edit': 'visible',   'view': 'visible'},                                                
        'reindexTranslations':      {'edit': 'visible',   'view': 'visible'},                                                
        },

    'SPSpeaker': {
        'id':                       {'edit': 'invisible', 'view': 'invisible'},                                                
        'title':                    {'edit': 'visible',   'view': 'visible'},                                                
        'firstName':                {'edit': 'visible',   'view': 'visible'},                                                
        'middleName':               {'edit': 'visible',   'view': 'visible'},                                                
        'lastName':                 {'edit': 'visible',   'view': 'visible'},                                                
        'suffix':                   {'edit': 'visible',   'view': 'visible'},                                                
        'email':                    {'edit': 'visible',   'view': 'visible'},                                                
        'jobTitles':                {'edit': 'visible',   'view': 'visible'},                                                
        'officeAddress':            {'edit': 'visible',   'view': 'visible'},                                                
        'officeCity':               {'edit': 'visible',   'view': 'visible'},                                                
        'officeState':              {'edit': 'visible',   'view': 'visible'},                                                
        'officePostalCode':         {'edit': 'visible',   'view': 'visible'},                                                
        'officePhone':              {'edit': 'visible',   'view': 'visible'},                                                
        'image':                    {'edit': 'visible',   'view': 'visible'},                                                
        'biography':                {'edit': 'visible',   'view': 'visible'},                                                
        'education':                {'edit': 'visible',   'view': 'visible'},                                                
        'website':                  {'edit': 'visible',   'view': 'visible'},                                                
        'speeches':                 {'edit': 'visible',   'view': 'visible'},                                                
        'nationality':              {'edit': 'visible',   'view': 'visible'},                                                
        'employer':                 {'edit': 'visible',   'view': 'visible'},                                                
        'socialPartnerGroup':       {'edit': 'visible',   'view': 'visible'},                                                
        'expertise':                {'edit': 'visible',   'view': 'visible'},                                                
        'country':                  {'edit': 'visible',   'view': 'visible'},                                                
        'subcategory':              {'edit': 'visible',   'view': 'visible'},                                                
        'multilingual_thesaurus':   {'edit': 'visible',   'view': 'visible'},                                                
        'nace':                     {'edit': 'visible',   'view': 'visible'},                                                
        'isNews':                   {'edit': 'visible',   'view': 'visible'},                                                
        'reindexTranslations':      {'edit': 'visible',   'view': 'visible'},                                                
    },

    }

